name: Build and Run CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make run
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      # with:
      #   submodules: recursive
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Build and run
      run: make run
