name: Build and Run CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Build and run
      run: make run
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    # Chatgpt code, might work, I don't know github ci
    - name: Install Git Bash
      run: |
        choco install git -y
        echo "##[add-path]$(command -v git)"
        echo "##[add-path]C:\Program Files\Git\usr\bin"
        echo "##[add-path]C:\Program Files\Git\mingw64\bin"
    - name: Build and run
      run: make run
